# Generated by Django 4.1.10 on 2023-09-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='biodata',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='instruc_biaodata/images'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='instructor',
            name='expertise',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='qualification',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
