# Generated by Django 4.1.10 on 2023-09-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_biodata_instructor_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='expected_salary',
            field=models.IntegerField(default=None),
        ),
    ]
