# Generated by Django 4.1.10 on 2023-09-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructor_expected_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
