# Generated by Django 4.1.10 on 2023-08-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='instructon',
            field=models.TextField(default=None),
        ),
    ]
