# Generated by Django 4.1.10 on 2023-09-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lecture', '0002_remove_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_course_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
