# Generated by Django 4.1.10 on 2023-09-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructor', '0004_alter_instructor_email'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('reason', models.CharField(choices=[('Leave', 'Leave'), ('Assignment', 'Assignment'), ('Support', 'Support')], max_length=20)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, default=None, null=True, upload_to='ticket/images')),
                ('instructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
