# Generated by Django 4.1.10 on 2023-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
