# Generated by Django 4.1.10 on 2023-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='student_enrolled',
            field=models.IntegerField(default=10),
        ),
    ]
